{{- range .Values.certs -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .certName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  secretName: {{ .certName }}
  dnsNames:
    {{- range .dnsNames }}
    - {{ . | quote}}
    {{- end }}
  issuerRef:
    name: selfsigned-intermediate-ca-issuer
    kind: ClusterIssuer
{{- end -}}