argo-cd:
  global:
    domain: argocd.test.local

  configs:
    params:
      server.insecure: true
    secret:
      annotations:
        "secret-generator.v1.mittwald.de/autogenerate": "admin.password"
        "secret-generator.v1.mittwald.de/type": "basic-auth"