apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-wait-for-crd"
  annotations:
    # This hook runs after the CRDs in crds/ are installed, but before the rest of the chart
    "helm.sh/hook": post-install, post-upgrade
    # Wait until the hook is ready (Job runs to completion)
    "helm.sh/hook-weight": "1" 
    # Clean up the job after it succeeds
    "helm.sh/hook-delete-policy": hook-succeeded 
spec:
  template:
    spec:
      containers:
      - name: wait-for-crd
        image: bitnami/kubectl:latest # Use a container with kubectl installed
        command: ['/bin/sh', '-c']
        args:
          - >
            echo "Waiting for the 'ingressroutes.traefik.io' CRD to be established...";
            until kubectl wait --for=condition=Established crd/ingressroutes.traefik.io --timeout=120s; do 
              sleep 5;
            done;
            echo "crd/ingressroutes.traefik.io CRD is established.";
      restartPolicy: OnFailure
      # Default argocd serviceaccount doesn't let us query CRDs
      serviceAccountName: argocd-application-controller 
  backoffLimit: 4
