apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-ingress
  annotations:
    "helm.sh/hook": pre-install
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rancher.test.local`)
      priority: 10
      services:
        - name: rancher
          port: 80
    - kind: Rule
      match: Host(`rancher.test.local`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: rancher
          port: 80
          scheme: h2c
  tls: {}
