apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-test-local
spec:
  secretName: wildcard-test-local-tls
  dnsNames:
    - "test.local"
    - "*.test.local"
  issuerRef:
    name: selfsigned-intermediate-ca-issuer
    kind: ClusterIssuer