# Wildcard cert for *.test.local which pihole forwards to localhost
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-test-local
  annotations:
    "helm.sh/hook": post-install
spec:
  secretName: wildcard-test-local-tls
  dnsNames:
    - "test.local"
    - "*.test.local"
  issuerRef:
    name: selfsigned-intermediate-ca-issuer
    kind: ClusterIssuer